services:
  - type: web
    name: chatgpt-in-slack
    env: production
    runtime: python
    repo: https://github.com/SYPartners/ChatGPT-in-Slack.git
    branch: main
    region: virginia  # Virginia, USA
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main_prod.py"
    healthCheckPath: /slack/events
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: chatgpt-redis
          property: connectionString

  - type: redis
    name: chatgpt-redis
    region: virginia  # Virginia, USA
    plan: starter
    ipAllowList: []  # Allow connections from all IPs