services:
  - type: web
    name: chatgpt-in-slack
    env: production
    runtime: node
    repo: https://github.com/SYPartners/ChatGPT-in-Slack.git
    branch: main
    region: virginia  # Virginia, USA
    plan: starter
    buildCommand: "npm install"
    startCommand: "node app.js"
    healthCheckPath: /healthz
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: chatgpt-redis
          property: connectionString

  - type: redis
    name: chatgpt-redis
    region: virginia  # Virginia, USA
    plan: starter
    ipAllowList: []  # Allow connections from all IPs