name: Sync from upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/seratch/ChatGPT-in-Slack.git
          git fetch upstream
          
      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit --allow-unrelated-histories || true
          
      - name: Push changes
        run: |
          git push origin main || echo "No changes to push"